# Generated by Django 5.0.7 on 2024-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReviewSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('reviewContent', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('createdAt', models.DateField()),
                ('review_email_id', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PUBLISHED', 'published'), ('NOT PUBLISHED', 'Not Published')], max_length=100)),
                ('genres', models.CharField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller')], max_length=10)),
            ],
        ),
    ]
